### ISSUE TITLE
Can not connect to MySQL 8 from PHPStorm

### ISSUE THREAD

**Issue by RokSiEu** [JetBrains/phpstorm-docker-images#16]
**Error**:
```
[08S01]
	Communications link failure

	The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
java.net.ConnectException: Connection refused: connect.

```

**docker-compose.yml**
```
version: '3.2'
services:
  webserver:
    build:
      context: ./php-74-apache-xdebug-30
      dockerfile: Dockerfile
    ports:
      - "6080:80"
    volumes:
      - ./:/var/www/html
    environment:
      #change the line below with your IP address
      XDEBUG_CONFIG: remote_host=192.168.2.108
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recipe
    ports:
      - "33306:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - webserver
    ports:
      - "8082:80"
  composer:
    tty: true
    container_name: "composer"
    image: composer:2
    command: [ "composer", "update" ]
    volumes:
      - ./:/app
``` 

**phpstorm**
```
PhpStorm 2020.3 Beta
Build #PS-203.5981.43, built on November 19, 2020
PhpStorm EAP User
Expiration date: December 19, 2020
Runtime version: 11.0.9+11-b1145.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
```
**mysql driver in phpstorm**
![image](https://user-images.githubusercontent.com/2094036/100271803-64d25480-2f5a-11eb-9b60-959928f16707.png)

**mysql port**
mysql> SHOW GLOBAL VARIABLES LIKE 'PORT';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| port          | 3306  |
+---------------+-------+
1 row in set (0.02 sec)

**Comment by emrzv** [comment]
Are you positive you are connecting to localhost:33306 and not localhost:3306?

**Comment by RokSiEu** [comment]
It works with MySQL 5.7, same configuration, so there has to be something with MySQL 8. I read that phpMyAdmin has same issues with latest version of MySQL.

**Comment by emrzv** [comment]
Please check the screencast: https://recordit.co/jRu4VCDTtE

**Comment by RokSiEu** [comment]
Issue has been resolved with little bit of changes in docker-compose.yml . I don't know if it has to do with Windows 10 as I tried few times previous config and it didn't work, even with changing port in PHPStorm. 
Thank you for your time @eugenemorozov-jb 
```
version: '3.2'
networks:
  mynet:
services:
  webserver:
    build:
      context: ./php-74-apache-xdebug-30
      dockerfile: Dockerfile
    ports:
      - "6080:80"
    volumes:
      - ./:/var/www/html
    environment:
      #change the line below with your IP address
      XDEBUG_CONFIG: remote_host=192.168.0.14
    networks:
      - mynet
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recipe
    ports:
      - "33306:3306"
    networks:
      - mynet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8082:80"
    networks:
      - mynet
  composer:
    tty: true
    container_name: "composer"
    image: composer:2
    command: [ "composer", "update" ]
    volumes:
      - ./:/app
```
