### ISSUE TITLE
Fail to parse to validation script output

### ISSUE THREAD

**Issue by final3987** [JetBrains/phpstorm-docker-images#9]
When I configure php cli interpreters 
it show Fail to parse to validation script output

my docker-compose
```
version: '3.6'
services:
  admin:
    build:
      context: ./docker/admin
    container_name: admin
    hostname: admin
    env_file:
      - ./env/.env
    networks:
      c61:
        ipv4_address: 10.10.10.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/admin:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
```
